### ISSUE TITLE
checkout and run doesn't work

### ISSUE THREAD

**Issue by KyleGobel** [nickytonline/ts-react-starter#13]
Just a heads up, checking out and running doesn't work.

Getting tslint errors for line endings incase you weren't aware.

**Comment by nickytonline** [comment]
Hmm weird. Thanks for the heads up. I'll take a peek at it this evening.

**Comment by nickytonline** [comment]
@KyleGobel I just did a fresh clone, ran `npm install` and then ran `npm start` and everything seems fine.  I also ran `npm run build` with no build issues. Are you still having the issue?

**Comment by KyleGobel** [comment]
Yeah.  It's an easy enough issue to fix on my side...though weird that you don't see it too..

Maybe 'cause i'm running on windows?

![image](https://cloud.githubusercontent.com/assets/4460054/24078384/6c7209a4-0c42-11e7-892a-28efde7602e7.png)

**Comment by nickytonline** [comment]
@KyleGobel, I'll take a look at this later this week but in the meantime, if you want to throw up a PR, you just need to remove this rule from the linter, https://github.com/nickytonline/ts-react-starter/blob/master/tslint.json#L22

**Comment by nickytonline** [comment]
@KyleGobel, grab this branch, https://github.com/nickytonline/ts-react-starter/tree/tslint-lf-windows-issue, and let me know if you still have the issue. I currently don't have access to a Windows machine to test this. Cheers, Nick
