### ISSUE TITLE
Issue in react-slingshot adding typescript support

### ISSUE THREAD

**Issue by Rajiv-Kulkarni** [nickytonline/ts-react-starter#9]
When I add a configureStore.ts like in the sample application in react-slingshot, I get error on:
const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose; // add support for Redux dev tools

The error says:
ERROR in [at-loader] src\store\configureStore.ts:33:35
    TS2339: Property '__REDUX_DEVTOOLS_EXTENSION_COMPOSE__' does not exist on type 'Window'.

Thanks.

**Comment by nickytonline** [comment]
Please report this issue here, https://github.com/typescriptcrew/ts-react-slingshot/issues
